### ISSUE TITLE
Broken links in 'Actas por estado', probably because of the space character present in the name of the estado (DTTO. CAPITAL, DELTA AMAC, LA GUAIRA)

### ISSUE THREAD

**Issue by rmbflp** [ielijose/actas-elecciones-2024#5]
When you click on the links of the 'Actas por estado' page for DTTO. CAPITAL, DELTA AMAC and LA GUAIRA, you get the message 'State not found'. I believe this occours because of the 'space' character present in the names of the states (between the two words). The links of other states with names with single words works.

**Comment by ielijose** [comment]
Thanks @rmbflp!
